AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/DisjunctiveAssignmentInConstructor:
  enabled: false
Metrics/PerceivedComplexity:
  Max: 40
Metrics/ParameterLists:
  Max: 15
  MaxOptionalParameters: 5
Metrics/BlockNesting:
  Max: 5
